### PR TITLE
ci: add node versions from 17 to 22

### PR DESCRIPTION
**Pull request by inigomarquinez**
This PR adds node versions from 17 to 22 to the CI so the tests are run for all the different nodejs versions apart from version 16.

### CODE REVIEW

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by blakeembrey** [comment]
Why is this useful? The library doesn’t use any node.js features so testing every version seems like overkill. And I’ll have to manually increment the latest version now?

**Comment by inigomarquinez** [comment]
> Why is this useful? The library doesn’t use any node.js features so testing every version seems like overkill. And I’ll have to manually increment the latest version now?

I thought this modification would be convenient for consistency with other repositories in the organisation, in which the ci runs on an array of node versions from the original to the latest active one (see [this](https://github.com/pillarjs/send/pull/229/files) or [this](https://github.com/pillarjs/finalhandler/pull/48/files)), so that you can easily verify that there is no problem with any of the nodejs versions.

Anyway, feel free to discard the PR if you don't find it interesting.

**Comment by blakeembrey** [comment]
Happy to accept all the other version bumps, but I'd prefer to keep the node.js versions as-is - min version + max version tests only.

**Pull request closed without merging**
