### PR TITLE
add umd

### PR DESCRIPTION
**Pull request by yurypaleev**

### CODE REVIEW

**Comment by wesleytodd** [comment]
Personally I am a 👎 to this.  I would suggest making a wrapper module, like `umd-path-to-regexp`, which wraps this up in it.

**Comment by yurypaleev** [comment]
@wesleytodd, and how can I use such module in the webpage?

**Comment by wesleytodd** [comment]
Depends on your tools and setup.  If you published a new node module which just required `path-to-regexp` and wrapped it in the UMD format, you could then include it in your browserify or webpack build just like any other module.  The UMD wrapper would take care of exposing the global variable for you if you needed it in other places on your website.

**Comment by yurypaleev** [comment]
What is the use of wrapping? If I need to use browserify or webpack to get the code, eventually. This additional code will solve the problem on many fronts.

**Comment by wesleytodd** [comment]
If you use webpack or browserify then this module needs no changes for you to be able to use it.  My assumption was you wanted UMD so you could get a global variable export or use it with require.js.

Either way, UMD is not something the core express/pillar team wants to support/add to modules.

**Comment by yurypaleev** [comment]
I would like to use it in the browser, keeping this module especially does not require anything to implement it.

**Comment by wesleytodd** [comment]
You can use it in the browser via webpack or browserify without any changes.  And it does have a cost to the maintainers and users to include UMD support directly in the module when it is not needed.

**Comment by yurypaleev** [comment]
Okay

**Pull request closed without merging**
