### PR TITLE
fix using asterisk inside param regexp

### PR DESCRIPTION
**Pull request by dougwilson**
This is my attempt at fixing https://github.com/strongloop/express/issues/2495 in the 0.1.x series :)

### CODE REVIEW

**Comment by blakeembrey** [comment]
Doesn't this break backward compatibility with `0.1.x`? I know there's a few intentional uses with it, which is why I've avoided touching it.

**Comment by dougwilson** [comment]
Sure, I guess in the technical sense, but I think I've heard enough from users that it is very unexpected that the stuff `:foo(<here>)` gets transformed in any way.

**Comment by blakeembrey** [comment]
Yes, I agree. But that's the gist of `1.x`. Couldn't you just upgrade to `1.x` then?

**Comment by dougwilson** [comment]
> Couldn't you just upgrade to 1.x then?

No, because that breaks paths like `/*`...

**Comment by blakeembrey** [comment]
@dougwilson Not since `1.2.x`. See https://github.com/pillarjs/path-to-regexp#asterisk.

**Comment by dougwilson** [comment]
Ah I see. So you're saying if I were to try 1.2.x in Express right now, all our tests would just pass?

**Comment by blakeembrey** [comment]
@dougwilson No guarantees, since there's a lot of other fixes, but I can give it a try :+1:

**Comment by dougwilson** [comment]
Darn it, we have an example with the path `'/files/:file(*)'`, so there goes the neighborhood :) I really wished I could fix this :)

**Comment by blakeembrey** [comment]
Just beat me to it. Yeah, that's the only major difference between `0.1` and `1.x` now. Well, plus there's a lot of new stuff in `1.x`.

**Comment by dougwilson** [comment]
Cool. I can't wait to get 5.0 out with 1.x. Thanks for keeping me honest :)

**Pull request closed without merging**
