### PR TITLE
tokensToFunction sensitive flags(options)

### PR DESCRIPTION
**Pull request by boringame**

### CODE REVIEW

**Comment by boringame** [comment]
Anybody home?

**Comment by blakeembrey** [comment]
Do you want to undo all the unrelated changes made?

**Comment by boringame** [comment]
Those Spaces could be an editor plug-in problem.Could you please check if there are any other questions? If not, I will resubmit them.

**Comment by blakeembrey** [comment]
@boringame That's my only concern.

**Pull request closed without merging**
